location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/open_vins
    name: open_vins
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: open_vins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_open_vins_estimator_plugin
    name: mrs_open_vins_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_open_vins_estimator_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_vins_republisher
    name: mrs_vins_republisher
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_vins_republisher
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_vins_imu_filter
    name: mrs_vins_imu_filter
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_vins_imu_filter
    scripts:
      - git submodule update --init --recursive
