location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/open_vins
    name: open_vins
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/open_vins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_open_vins_estimator_plugin
    name: mrs_open_vins_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_open_vins_estimator_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/vins_republish
    name: vins_republish
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/vins_republish
    scripts:
      - git submodule update --init --recursive
