# /uav1/run_subscribe_msckf:
#   ros__parameters:
#     loop_depth:
#       enable_pub_plugins:
#       - image_transport/compressed
#       - image_transport/raw

/uav1/bluefox2_single:
  ros__parameters:
    remappings:
      /uav1/image_raw: /uav1/image_raw